// WARNING: Please don't edit this file. It was generated by Swift/WinRT v0.0.1
// swiftlint:disable all
import Foundation
@_spi(WinRTInternal) @_spi(WinRTImplements) import WindowsFoundation
import CWinRT

/// [Open Microsoft documentation](https://learn.microsoft.com/windows/windows-app-sdk/api/winrt/microsoft.graphics.directx.directxalphamode)
public typealias DirectXAlphaMode = __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXAlphaMode
/// [Open Microsoft documentation](https://learn.microsoft.com/windows/windows-app-sdk/api/winrt/microsoft.graphics.directx.directxpixelformat)
public typealias DirectXPixelFormat = __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat
extension WinAppSDK.DirectXAlphaMode {
    public static var unspecified : WinAppSDK.DirectXAlphaMode {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXAlphaMode_Unspecified
    }
    public static var premultiplied : WinAppSDK.DirectXAlphaMode {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXAlphaMode_Premultiplied
    }
    public static var straight : WinAppSDK.DirectXAlphaMode {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXAlphaMode_Straight
    }
    public static var ignore : WinAppSDK.DirectXAlphaMode {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXAlphaMode_Ignore
    }
}
extension WinAppSDK.DirectXAlphaMode: @retroactive Hashable, @retroactive Codable {}

extension WinAppSDK.DirectXPixelFormat {
    public static var unknown : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_Unknown
    }
    public static var r32g32b32a32Typeless : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_R32G32B32A32Typeless
    }
    public static var r32g32b32a32Float : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_R32G32B32A32Float
    }
    public static var r32g32b32a32uInt : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_R32G32B32A32UInt
    }
    public static var r32g32b32a32Int : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_R32G32B32A32Int
    }
    public static var r32g32b32Typeless : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_R32G32B32Typeless
    }
    public static var r32g32b32Float : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_R32G32B32Float
    }
    public static var r32g32b32uInt : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_R32G32B32UInt
    }
    public static var r32g32b32Int : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_R32G32B32Int
    }
    public static var r16g16b16a16Typeless : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_R16G16B16A16Typeless
    }
    public static var r16g16b16a16Float : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_R16G16B16A16Float
    }
    public static var r16g16b16a16uIntNormalized : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_R16G16B16A16UIntNormalized
    }
    public static var r16g16b16a16uInt : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_R16G16B16A16UInt
    }
    public static var r16g16b16a16IntNormalized : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_R16G16B16A16IntNormalized
    }
    public static var r16g16b16a16Int : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_R16G16B16A16Int
    }
    public static var r32g32Typeless : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_R32G32Typeless
    }
    public static var r32g32Float : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_R32G32Float
    }
    public static var r32g32uInt : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_R32G32UInt
    }
    public static var r32g32Int : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_R32G32Int
    }
    public static var r32g8x24Typeless : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_R32G8X24Typeless
    }
    public static var d32FloatS8X24UInt : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_D32FloatS8X24UInt
    }
    public static var r32FloatX8X24Typeless : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_R32FloatX8X24Typeless
    }
    public static var x32TypelessG8X24UInt : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_X32TypelessG8X24UInt
    }
    public static var r10g10b10a2Typeless : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_R10G10B10A2Typeless
    }
    public static var r10g10b10a2uIntNormalized : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_R10G10B10A2UIntNormalized
    }
    public static var r10g10b10a2uInt : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_R10G10B10A2UInt
    }
    public static var r11g11b10Float : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_R11G11B10Float
    }
    public static var r8g8b8a8Typeless : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_R8G8B8A8Typeless
    }
    public static var r8g8b8a8uIntNormalized : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_R8G8B8A8UIntNormalized
    }
    public static var r8g8b8a8uIntNormalizedSrgb : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_R8G8B8A8UIntNormalizedSrgb
    }
    public static var r8g8b8a8uInt : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_R8G8B8A8UInt
    }
    public static var r8g8b8a8IntNormalized : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_R8G8B8A8IntNormalized
    }
    public static var r8g8b8a8Int : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_R8G8B8A8Int
    }
    public static var r16g16Typeless : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_R16G16Typeless
    }
    public static var r16g16Float : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_R16G16Float
    }
    public static var r16g16uIntNormalized : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_R16G16UIntNormalized
    }
    public static var r16g16uInt : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_R16G16UInt
    }
    public static var r16g16IntNormalized : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_R16G16IntNormalized
    }
    public static var r16g16Int : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_R16G16Int
    }
    public static var r32Typeless : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_R32Typeless
    }
    public static var d32Float : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_D32Float
    }
    public static var r32Float : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_R32Float
    }
    public static var r32uInt : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_R32UInt
    }
    public static var r32Int : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_R32Int
    }
    public static var r24g8Typeless : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_R24G8Typeless
    }
    public static var d24uIntNormalizedS8UInt : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_D24UIntNormalizedS8UInt
    }
    public static var r24uIntNormalizedX8Typeless : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_R24UIntNormalizedX8Typeless
    }
    public static var x24TypelessG8UInt : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_X24TypelessG8UInt
    }
    public static var r8g8Typeless : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_R8G8Typeless
    }
    public static var r8g8uIntNormalized : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_R8G8UIntNormalized
    }
    public static var r8g8uInt : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_R8G8UInt
    }
    public static var r8g8IntNormalized : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_R8G8IntNormalized
    }
    public static var r8g8Int : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_R8G8Int
    }
    public static var r16Typeless : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_R16Typeless
    }
    public static var r16Float : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_R16Float
    }
    public static var d16uIntNormalized : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_D16UIntNormalized
    }
    public static var r16uIntNormalized : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_R16UIntNormalized
    }
    public static var r16uInt : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_R16UInt
    }
    public static var r16IntNormalized : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_R16IntNormalized
    }
    public static var r16Int : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_R16Int
    }
    public static var r8Typeless : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_R8Typeless
    }
    public static var r8uIntNormalized : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_R8UIntNormalized
    }
    public static var r8uInt : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_R8UInt
    }
    public static var r8IntNormalized : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_R8IntNormalized
    }
    public static var r8Int : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_R8Int
    }
    public static var a8uIntNormalized : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_A8UIntNormalized
    }
    public static var r1uIntNormalized : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_R1UIntNormalized
    }
    public static var r9g9b9e5SharedExponent : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_R9G9B9E5SharedExponent
    }
    public static var r8g8b8g8uIntNormalized : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_R8G8B8G8UIntNormalized
    }
    public static var g8r8g8b8uIntNormalized : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_G8R8G8B8UIntNormalized
    }
    public static var bc1Typeless : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_BC1Typeless
    }
    public static var bc1uIntNormalized : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_BC1UIntNormalized
    }
    public static var bc1uIntNormalizedSrgb : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_BC1UIntNormalizedSrgb
    }
    public static var bc2Typeless : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_BC2Typeless
    }
    public static var bc2uIntNormalized : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_BC2UIntNormalized
    }
    public static var bc2uIntNormalizedSrgb : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_BC2UIntNormalizedSrgb
    }
    public static var bc3Typeless : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_BC3Typeless
    }
    public static var bc3uIntNormalized : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_BC3UIntNormalized
    }
    public static var bc3uIntNormalizedSrgb : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_BC3UIntNormalizedSrgb
    }
    public static var bc4Typeless : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_BC4Typeless
    }
    public static var bc4uIntNormalized : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_BC4UIntNormalized
    }
    public static var bc4IntNormalized : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_BC4IntNormalized
    }
    public static var bc5Typeless : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_BC5Typeless
    }
    public static var bc5uIntNormalized : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_BC5UIntNormalized
    }
    public static var bc5IntNormalized : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_BC5IntNormalized
    }
    public static var b5g6r5uIntNormalized : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_B5G6R5UIntNormalized
    }
    public static var b5g5r5a1uIntNormalized : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_B5G5R5A1UIntNormalized
    }
    public static var b8g8r8a8uIntNormalized : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_B8G8R8A8UIntNormalized
    }
    public static var b8g8r8x8uIntNormalized : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_B8G8R8X8UIntNormalized
    }
    public static var r10g10b10xrBiasA2UIntNormalized : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_R10G10B10XRBiasA2UIntNormalized
    }
    public static var b8g8r8a8Typeless : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_B8G8R8A8Typeless
    }
    public static var b8g8r8a8uIntNormalizedSrgb : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_B8G8R8A8UIntNormalizedSrgb
    }
    public static var b8g8r8x8Typeless : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_B8G8R8X8Typeless
    }
    public static var b8g8r8x8uIntNormalizedSrgb : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_B8G8R8X8UIntNormalizedSrgb
    }
    public static var bc6hTypeless : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_BC6HTypeless
    }
    public static var bc6h16UnsignedFloat : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_BC6H16UnsignedFloat
    }
    public static var bc6h16Float : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_BC6H16Float
    }
    public static var bc7Typeless : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_BC7Typeless
    }
    public static var bc7uIntNormalized : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_BC7UIntNormalized
    }
    public static var bc7uIntNormalizedSrgb : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_BC7UIntNormalizedSrgb
    }
    public static var ayuv : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_Ayuv
    }
    public static var y410 : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_Y410
    }
    public static var y416 : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_Y416
    }
    public static var nv12 : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_NV12
    }
    public static var p010 : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_P010
    }
    public static var p016 : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_P016
    }
    public static var opaque420 : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_Opaque420
    }
    public static var yuy2 : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_Yuy2
    }
    public static var y210 : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_Y210
    }
    public static var y216 : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_Y216
    }
    public static var nv11 : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_NV11
    }
    public static var ai44 : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_AI44
    }
    public static var ia44 : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_IA44
    }
    public static var p8 : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_P8
    }
    public static var a8p8 : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_A8P8
    }
    public static var b4g4r4a4uIntNormalized : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_B4G4R4A4UIntNormalized
    }
    public static var p208 : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_P208
    }
    public static var v208 : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_V208
    }
    public static var v408 : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_V408
    }
    public static var samplerFeedbackMinMipOpaque : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_SamplerFeedbackMinMipOpaque
    }
    public static var samplerFeedbackMipRegionUsedOpaque : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_SamplerFeedbackMipRegionUsedOpaque
    }
    public static var a4b4g4r4 : WinAppSDK.DirectXPixelFormat {
        __x_ABI_CMicrosoft_CGraphics_CDirectX_CDirectXPixelFormat_A4B4G4R4
    }
}
extension WinAppSDK.DirectXPixelFormat: @retroactive Hashable, @retroactive Codable {}

